### ISSUE TITLE
gWavDiss function: object 'tmp2samp' not found (and SNP file format)

### ISSUE THREAD

**Issue by jbruxaux** [jesserlasky/WaveletSpatialGenetic#1]
Hi!

I'm going through your script, and found a small bug / error.
I imported my coordinates under a different name than 'tmp2samp', and changed the script accordingly.
Until I reached the gWavDiss function, where the object is apparently not needed in the command. But I got this error anyway:

> Error in nrow(tmp2samp) : object 'tmp2samp' not found 

I suggest that if you want it to run easily for everyone, you could either write clearly that the tmp2samp name has to be used and not changed, or ask in the gWavDiss function what the name of the coordinates file is.

Another minor point, but it took me some time to generate the SNP file from my vcf. I ended up using plink to create a structure file, and imported it after skipping the two first rows (and the first column). It works fine.

Hope it helps!

Jade

**Comment by jesserlasky** [comment]
The issue with `gWavDiss()` has now been fixed.
