### ISSUE TITLE
NaN in null distribution

### ISSUE THREAD

**Issue by jbruxaux** [jesserlasky/WaveletSpatialGenetic#2]
Hi!

Another question...
When I run the analysis on my dataset, I get some NaN when producing the null_wavGdis object for the lowest values of scale. I then get an error when I reach the stage of CI estimation:
```
Error in quantile.default(apply(null_wavGdis[[i]], 2, mean), probs = c(0.025,  : 
  missing values and NaN's not allowed if 'na.rm' is FALSE

```
Should I add a na.rm=T in the apply? So far I just removed completely those smallest values.

Thanks for your answer!

Jade

**Comment by jesserlasky** [comment]
This may occur at very small scales if you don't have any samples that
close. I would maybe not choose such a small scale.

Sorry for the delay. I am working to get this manuscript accepted first, I
need to take care of that, and then I can devote more time to helping with
bugs. Thank you for your interest!

**Comment by jesserlasky** [comment]
I have also fixed this is the new version.
