### ISSUE TITLE
More than one individual for each population (individuals shared same coordinates)

### ISSUE THREAD

**Issue by zhiqinlong** [jesserlasky/WaveletSpatialGenetic#3]
Hi Jesse,

This is an amazing tool, and I am really impressed by it. I noticed that in your example, each population only has one individual. Normally, in our data, there are more than one individual per population. If I use the SNP file (0/1/2) with all individuals, there will be many zero distances between individuals from the same population (Distance matrix). Do you think I should use population-level data as the sample file and allele frequencies as the SNP file instead?

Additionally, could you please provide some code to help convert Long/Lat to kilometers?
Loking forwrd to your reply!
Best,
Zhiqin

**Comment by jesserlasky** [comment]
Thank you Zhiqin!
Yes - you should just calculate the allele frequency within the population and use that as your input. This is what I did with Arabidopsis in the paper.
For calculating distances, I use the distVincentyEllipsoid function in the R package geosphere:
https://cran.r-project.org/web/packages/geosphere/geosphere.pdf

Good luck and I would be happy to provide any more assistance.

Jesse

**Comment by zhiqinlong** [comment]
Hi Jesse
Thank you so much for your help. I also found that when all individuals show a 0/1 genotype, the standard deviation will be 0, and this situation can't be excluded by filtering minor allele frequency (MAF). The tmpW/locSD function will return all 'inf', and then the optim function will return an error. Could you please add a function to address this issue?

This is a really great tool, and I truly hope many people will use it. I'll continue to discuss any problems I encounter during my analysis.

Best regards,
Zhiqin

**Comment by jesserlasky** [comment]
Yes I realized this belatedly - however, if all individuals are
heterozygotes it is probably a mapping error due to paralogy. I will add
this filtering automatically based on genotype variance ASAP

**Comment by jesserlasky** [comment]
I have added 2 lines of code to remove such loci and also added a recommendation to filter these loci on the landing page.

**Comment by zhiqinlong** [comment]
Hi Jess,

Thank you so much for your help. I have another question and would really appreciate your insights.

I found that there are no SNPs with a q-value below 0.05. Given this, what would be the best approach to identify candidate SNPs? Would ranking them and selecting the top 1% be appropriate?

Also, I noticed your analysis doesn’t distinguish between regions under positive selection and those linked to local adaptation. In my view, local adaptation allele may be considered as having experienced positive selection, either currently or in the past. Do you think it’s valid to consider regions detected by this method as selective sweeps? 

Thank you again for your time and expertise.
Best,
Zhiqin

**Comment by jesserlasky** [comment]
Generally I think genome-scan p-values are not well-calibrated, so I don't think a lack of significance necessarily means you didn't identify any locally-adapted loci. What you do with the output depends on your goals, but yes I think the top ranked SNPs have relatively more evidence of local adaptation and may be worth following up on in some way.

I don't think there is enough here with our method to identify local sweeps, I think some haplotype related statistics would be required (e.g. those designed specifically for sweeps).

**Comment by zhiqinlong** [comment]
Hi Jess, 
Thanks for your time and valuable ideas. 
Best,
Zhiqin
